### ISSUE TITLE
为什么这段代码中的permutation中的参数不是string呢？

### ISSUE THREAD

**Issue by tonywangcn** [Peter-Liang/CodeWars-Python#1]
为什么这段代码中的permutation中的参数不是string呢？

https://github.com/Peter-Liang/CodeWars-Python/blob/master/solutions/Permutations.py
permutations(string[:i] + string[i + 1:])

**Comment by Peter-Liang** [comment]
string[:i] + string[i + 1:]的意思是两个字符串相加，但去掉了第i个字符。
这使得每次递归调用permutations传进的字符串都比上一次短，短到长度只剩2时，就能跳出递归，返回结果。

如果只传入整个string，每次调用都跟上一次的参数一样，类似于死循环，结果就是调用堆栈一直增长直到溢出。
